[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.10.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "/"
  NODE_ENV = "production"
  NEXTAUTH_URL = "https://globexpay.netlify.app"
  NEXTAUTH_SECRET = "your-secret-key-at-least-32-chars-long"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https: api.royalpay.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
